spring:
  datasource:
    url: jdbc:mysql://localhost:3306/untitled_pro
    username: root
    password: Abhideva@1110
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  data:
    web:
      pageable:
        default-page-size: 20

server:
  servlet:
    context-path: /untitled_pro
  port: 8080

springdoc:
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    groups-order: asc
    disable-swagger-default-url: true
    docUrl: http://localhost:8080/untitled_pro

cloud:
  aws:
    region:
      auto: false
      static: ap-south-1
    stack:
      auto: false

logging:
  level:
    org:
      hibernate:
        stat: info
        type:
          descriptor:
            sql: info
